import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>First App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>My first Next.js project&nbsp;</p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              with{" "}
              <Image
                src="/next.svg"
                alt="Next Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <a
            href="https://www.microsoft.com/"
            className={styles.glowOnHover}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Hello, Microsoft! <span>-&gt;</span>
            </h2>
            <p className={inter.className}>Hover on me xD!</p>
          </a>
        </div>
      </main>
    </>
  );
}
